apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-list-from-is
    app.kubernetes.io/component: todo-list-from-is
    app.kubernetes.io/instance: todo-list-from-is
    app.kubernetes.io/name: todo-list
  name: todo-list-from-is
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: todo-list-from-is
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: todo-list-from-is
    spec:
      containers:
      - env:
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: todo-list-postgres-account
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: USER
              name: todo-list-postgres-account              
        - name: SPRING_DATASOURCE_PASSWORD
          value: "$(DATASOURCE_PASSWORD)"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-from-source:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "$(DATASOURCE_USERNAME)"
        image: docker.io/shawnyang/todo-list@sha256:c8ec1b87dbf76982a2ef1c9b04ab07090361f0c027fe90ac93fb58878f834ceb
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: todo-list
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30